name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build frontend
        run: |
          npm run build

      - name: Set up SSH key
        env:
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$GCP_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add GCP to known_hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Pull latest changes and build on GCP
        env:
          GCP_HOST: ${{ secrets.GCP_VM_IP }}
          GCP_USER: ${{ secrets.GCP_VM_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $GCP_USER@$GCP_HOST << 'EOF'
            cd ~/nest-project-react
            git pull origin main
            npm install
            npm run build
            sudo cp -r build/* /var/www/html/react
            sudo systemctl restart nginx
          EOF
