name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build frontend
        run: |
          npm run build

      - name: Pull latest changes and build on GCP
        env:
          GCP_HOST: ${{ secrets.GCP_VM_IP }}
          GCP_USER: ${{ secrets.GCP_VM_USER }}
          GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$GCP_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no $GCP_USER@$GCP_HOST << 'EOF'
            cd ~/nest-project-react  # 클론한 디렉터리로 이동
            git pull origin main      # 최신 코드 가져오기

            npm install
            npm run build

            # 빌드 결과물을 Nginx 제공 디렉터리로 복사
            sudo cp -r build/* /var/www/html/react
            sudo systemctl restart nginx
          EOF
